### ISSUE TITLE
Custom tags

### ISSUE THREAD

**Issue by baccioly** [peterhudec/image-metadata-cruncher#1]
Hi there,

I got a set of images here and they have a "Keywords" tag in it.
I really don't know if the tag "Keywords" is a default tag or if it is a custom tag inserted later on.
Is there a way to access this list of comma separated words using Image Metadata Cruncher?

Best regards,
Bruno Accioly

**Comment by peterhudec** [comment]
Could yo send me one of the images to e-mail so I can take a look on it?
