### ISSUE TITLE
Fatal error occurs

### ISSUE THREAD

**Issue by whstaley** [peterhudec/image-metadata-cruncher#3]
I loaded the plug-in Image Metadata Cruncher with no changes to settings. When I try to upload an image I get the following error;

 Fatal error: Call to undefined function exif_read_data() in \frigga\home\users\web\b2321\ph.d30034043\blog\wp-content\plugins\image-metadata-cruncher\image-metadata-cruncher.php on line 218 

I am using WP ver 3.5.1.

 Bill
bill@frgpond.com

**Comment by peterhudec** [comment]
The `exif_read_data()` is part of the **Exif** library which you apparently have note enabled.
As stated [here](http://www.php.net/manual/en/exif.installation.php), you need to configure your PHP with --enable-exif to get it work.
